apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: andrewkarma/authentservice
      context: src/services/authentservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
manifests:
  kustomize:
    paths:
      - kubernetes-manifests
deploy:
  kubectl: {}
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        diskSizeGb: 300
        machineType: N1_HIGHCPU_32
        timeout: 5000s
  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/7/docker/dockerfile
        value: Dockerfile.debug
  - name: network-policies
    patches:
      - op: add
        path: /manifests/kustomize/paths/1
        value: kustomize/components/network-policies
